export const data = [
  {
    id: 1,
    name: "John Doe",
    age: 25,
    city: "New York",
    email: "example@gmail.com",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 30,
    city: "Los Angeles",
    email: "example@gmail.com",
  },
  {
    id: 3,
    name: "Michael Jamie ",
    age: 15,
    city: "Chicago",
    email: "example@gmail.com",
  },
  {
    id: 4,
    name: "Michael Johnson ",
    age: 33,
    city: "Washington DC",
    email: "example@gmail.com",
  },
  {
    id: 5,
    name: "Michael Jackson ",
    age: 23,
    city: "Houston",
    email: "example@gmail.com",
  },
  {
    id: 6,
    name: "Stewart Johnson",
    age: 44,
    city: "Houston",
    email: "example@gmail.com",
  },
  {
    id: 7,
    name: "Tim Josh",
    age: 41,
    city: "HCM City",
    email: "example@gmail.com",
  },
  {
    id: 8,
    name: "Davis Cooper",
    age: 23,
    city: "Texas",
    email: "example@gmail.com",
  },
  {
    id: 9,
    name: "Davis Cooper Junior",
    age: 23,
    city: "New York",
    email: "example@gmail.com",
  },
  {
    id: 10,
    name: "Davis Cock",
    age: 33,
    city: "New York",
    email: "example@gmail.com",
  },
  {
    id: 11,
    name: "Jordan Klepper",
    age: 34,
    city: "Texas",
    email: "example@gmail.com",
  },
];
